#!/bin/bash
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
#     mpll: program which merges the functionalities of perltex and lualatex
#
#     Copyright (C) 2012 Jean Forget
# 
#     This program is free software; you can redistribute it and/or modify
#     it under the same terms as Perl: either the Artistic License,
#     or the GNU General Public License as published by
#     the Free Software Foundation; either version 1, or (at your option)
#     any later version.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License and
#     the Artistic License along with this program; if not, write to the Free
#     Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
#     02111-1307, USA.

function usage {
  echo 'usage (TODO)'
}

for i in $*
do
  case $i in
    -v | --version)
      echo This is mpll version 1.0
      echo ------------
      lualatex -v
      echo ------------
      echo no version info for perltex
      exit
      ;;
    --help)
      usage
      exit
      ;;
    --*)
      ;;
    *)
      nom=$i
      echo "nom = $nom"
      ;;
  esac
done

perltex --latex=lualatex --nosafe --jobname=$nom $*
